version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Run build
          command: ./gradlew compileJava compileTestJava --stacktrace
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Test coverage report
          command: ./gradlew jacocoTestReport
      - run:
          name: Send test coverage report to CodeCov
          command: |
            bash <(curl -s https://codecov.io/bash)
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r build/reports/jacoco/test/jacocoTestReport.xml
